apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: contapics-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: contapics.local
      http:
        paths:
          - path: /api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: contapics-backend-backend
                port:
                  number: 8080
