image:
  repository: contapics-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

env:
  db:
    host: contapics-postgres-postgresql
    port: "5432"
    name: mydb

  corsAllowedOrigin: "*"

  aws:
    region: us-east-1
    s3Endpoint: http://minio:9000
    bucketName: contapics

  ocrServiceUrl: http://ocr-service:5001

secrets:
  db:
    user: myuser
    password: mypassword

  aws:
    accessKeyId: minio
    secretAccessKey: minio123
