apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "contapics-ocr.fullname" . }}
data:
  AWS_REGION: {{ .Values.env.aws.region | quote }}
  AWS_S3_ENDPOINT: {{ .Values.env.aws.s3Endpoint | quote }}
  AWS_S3_BUCKET_NAME: {{ .Values.env.aws.bucketName | quote }}
  OCR_SERVICE_URL: {{ .Values.env.ocrServiceUrl | quote }}
