apiVersion: v1
kind: Service
metadata:
  name: {{ include "contapics-minio.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: {{ .Values.service.consolePort }}
  selector:
    app: {{ include "contapics-minio.fullname" . }}
