apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contapics-frontend.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "contapics-frontend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "contapics-frontend.fullname" . }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BACKEND_URL
              value: {{ .Values.env.backendUrl | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: frontend-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: frontend-config
          configMap:
            name: contapics-frontend-config
