apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "contapics-backend.fullname" . }}
data:
  DB_HOST: {{ .Values.env.db.host | quote }}
  DB_PORT: {{ .Values.env.db.port | quote }}
  DB_NAME: {{ .Values.env.db.name | quote }}

  CORS_ALLOWED_ORIGIN: {{ .Values.env.corsAllowedOrigin | quote }}

  AWS_REGION: {{ .Values.env.aws.region | quote }}
  AWS_S3_ENDPOINT: {{ .Values.env.aws.s3Endpoint | quote }}
  AWS_S3_BUCKET_NAME: {{ .Values.env.aws.bucketName | quote }}

  OCR_SERVICE_URL: {{ .Values.env.ocrServiceUrl | quote }}
